languageCode = "en-uk"
title = "Chip Design and Verification"

baseurl = "https://kuleuven-diepenbeek.github.io/course_cdandverif/"
# fix for subdir baseurl, see https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

theme = "hugo-theme-learn"
publishDir = "docs"
enableEmoji = true
enableRobotsTXT = true
pygmentsCodefences = true


# for .Lastmod to work with .GitInfo: --enableGitInfo https://gohugo.io/variables/git/
enableGitInfo = true


# Since Hugo v0.100.0 - blackfriday is no longer available
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        enable = false
        escapedSpace = false
#      [markup.goldmark.extensions.typographer]
#        apostrophe = '&rsquo;'
#        disable = false
#        ellipsis = '&hellip;'
#        emDash = '&mdash;'
#        enDash = '&ndash;'
#        leftAngleQuote = '&laquo;'
#        leftDoubleQuote = '&ldquo;'
#        leftSingleQuote = '&lsquo;'
#        rightAngleQuote = '&raquo;'
#        rightDoubleQuote = '&rdquo;'
#        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


# # for new Hugo 0.6x, markup changed to CommonMark.
# [markup]
#   defaultMarkdownHandler = "blackfriday"
#   [markup.blackFriday]
#     skipHTML = false
#   [markup.highlight]
#     anchorLineNos = false
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineAnchors = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     style = "monokai"
#     tabWidth = 4
# 
# [blackfriday]
#   hrefTargetBlank = true

[taxonomies]
    tag = "tags"

[params]
    disableComments = true
    themeVariant = "kul"
    disableInlineCopyToClipBoard = true
    ordersectionsby = "weight"
    disableLandingPageButton = true # Disable the "Home" link in the navigation menu

# see https://learn.netlify.com/en/basics/configuration/
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Author]
  name = "Nele Mentens and Jo Vliegen"
  email = "<i>fname</i>.<i>lname</i>A T<i>kuleuven.be</i>"

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> Toledo"
identifier = "tol"
url = "https://toledo.kuleuven.be/"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-university'></i> ECTS Sheet"
identifier = "stud"
url = "https://studiegidswww.uhasselt.be/opleidingsonderdeel.aspx?a=2023&i=3467&n=4&t=04#anker46108"
weight = 1
